'use client';
import {useEffect,useMemo,useState} from 'react';
import type {ReactNode} from 'react';
import {Activity,AlertTriangle,Bell,Building2,ChevronDown,ChevronRight,Clock3,Flame,Gauge,Layers3,MapPin,RefreshCw,Search,ShieldCheck,Satellite,Sparkles,Target,Wifi,Zap} from 'lucide-react';
import LiveMap,{type MapLayers,type MapMode,type ThermalSignal} from '@/components/LiveMap';

type Explanation={feature:string;contribution:number};
type Event={id:string;name:string;lat:number;lon:number;cls:string;confidence:number;risk:string;brightness:number;persistence:number;distance:number;time:string;detectedAt?:string;source?:string;landCover?:string;facility?:string;facilityType?:string;satellite?:string;frp?:number;firmsConfidence?:number;persistenceObservations?:number;persistenceWindow?:number;explanations?:Explanation[]};
const seed:Event[]=[
{id:'TG-1042',name:'Industrial cluster · Gujarat',lat:22.31,lon:72.61,cls:'Industrial Fire',confidence:91,risk:'CRITICAL',brightness:342,persistence:88,distance:.7,time:'14:32 IST',source:'DEMO',landCover:'industrial'},
{id:'TG-1037',name:'Gas infrastructure · Rajasthan',lat:27.17,lon:73.21,cls:'Gas Flare',confidence:96,risk:'HIGH',brightness:329,persistence:97,distance:1.1,time:'13:58 IST',source:'DEMO',landCover:'industrial'},
{id:'TG-1028',name:'Agricultural belt · Haryana',lat:29.06,lon:76.08,cls:'Crop Burning',confidence:86,risk:'MODERATE',brightness:318,persistence:43,distance:18.4,time:'13:41 IST',source:'DEMO',landCover:'cropland'},
{id:'TG-1019',name:'Forest edge · Odisha',lat:20.26,lon:84.27,cls:'Wildfire',confidence:84,risk:'HIGH',brightness:337,persistence:29,distance:31.2,time:'12:47 IST',source:'DEMO',landCover:'forest'}];
const fallbackXai:Explanation[]=[{feature:'Industrial proximity',contribution:.42},{feature:'Thermal intensity',contribution:.31},{feature:'Historical persistence',contribution:.24},{feature:'FIRMS confidence',contribution:.18},{feature:'Forest proximity',contribution:-.06}];
function toEvent(e:any):Event{return {id:e.id,name:e.location||e.name||`${e.classification} · ${Number(e.latitude).toFixed(2)}, ${Number(e.longitude).toFixed(2)}`,lat:Number(e.latitude),lon:Number(e.longitude),cls:e.classification,confidence:Number(e.confidence)||0,risk:e.risk||'MODERATE',brightness:Number(e.brightnessKelvin)||0,persistence:Number(e.persistenceScore)||0,distance:Number(e.industrialDistance)||99,time:new Date(e.detectedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})+' IST',detectedAt:e.detectedAt,source:e.source,landCover:e.landCover,facility:e.facility,facilityType:e.facilityType,satellite:e.satellite,frp:Number(e.frp)||undefined,firmsConfidence:Number(e.firmsConfidence)||Number(e.confidence)||undefined,persistenceObservations:Number(e.persistenceObservations)||undefined,persistenceWindow:Number(e.persistenceWindow)||30,explanations:e.explanations||fallbackXai};}
function riskClass(r:string){return r.toLowerCase();}

export default function Home(){
 const[events,setEvents]=useState<Event[]>(seed),[thermalSignals,setThermalSignals]=useState<ThermalSignal[]>([]),[selected,setSelected]=useState<Event>(seed[0]),[q,setQ]=useState(''),[filter,setFilter]=useState('ALL'),[source,setSource]=useState('DEMO_DATA'),[loading,setLoading]=useState(true),[analyzing,setAnalyzing]=useState(false),[sim,setSim]=useState(false),[toast,setToast]=useState(''),[alerts,setAlerts]=useState<string[]>([]),[active,setActive]=useState('home'),[layersOpen,setLayersOpen]=useState(false),[mapMode,setMapMode]=useState<MapMode>('hotspots'),[mapLayers,setMapLayers]=useState<MapLayers>({thermal:true,markers:true,halos:true,labels:true}),[timeWindow,setTimeWindow]=useState(7),[technical,setTechnical]=useState(false),[brightness,setBrightness]=useState(350),[persistence,setPersistence]=useState(82),[simLocation,setSimLocation]=useState('Ahmedabad, Gujarat');
 const visible=useMemo(()=>events.filter(e=>(filter==='ALL'||e.risk===filter)&&(!q||`${e.id} ${e.name} ${e.cls}`.toLowerCase().includes(q.toLowerCase()))),[events,filter,q]);
 const visibleSignals=useMemo(()=>{if(!thermalSignals.length)return[];const newest=thermalSignals.reduce((max,x)=>x.date>max?x.date:max,'');const cutoff=new Date(`${newest}T00:00:00Z`);cutoff.setUTCDate(cutoff.getUTCDate()-(timeWindow-1));const from=cutoff.toISOString().slice(0,10);return thermalSignals.filter(x=>x.date>=from)},[thermalSignals,timeWindow]);
 const critical=events.filter(e=>e.risk==='CRITICAL'||e.risk==='HIGH').length,persistent=events.filter(e=>e.persistence>=70).length,avg=events.length?events.reduce((a,e)=>a+e.confidence,0)/events.length:0;
 const scroll=(id:string)=>{setActive(id);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});};
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/events',{cache:'no-store'});const d=await r.json();if(d.ok&&d.events?.length){const mapped=d.events.map(toEvent);setEvents(mapped);setSelected(mapped[0]);setSource(d.source||'DEMO_DATA');}}catch{setToast('Refresh failed. Showing current intelligence.')}finally{setLoading(false)}};
 useEffect(()=>{load();fetch('/data/firms-recent.json').then(r=>r.json()).then(d=>setThermalSignals(d.observations||[])).catch(()=>setToast('FIRMS density archive could not be loaded.'));const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)},[toast]);
 const selectEvent=(e:Event)=>{setSelected(e);setTechnical(false)};
 const analyze=async(e:Event)=>{setSelected(e);setAnalyzing(true);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({latitude:e.lat,longitude:e.lon,days:timeWindow,windowDays:timeWindow,brightnessKelvin:e.brightness,persistence:e.persistence,industrialDistanceKm:e.distance,landCover:e.landCover&&e.landCover!=='unknown'?e.landCover:undefined})});const d=await r.json();if(!d.ok)throw new Error(d.error);const h=d.event.hotspot,res=d.event.result,p=d.event.persistence||{},facility=d.event.nearestFacility,updated={...e,lat:h.latitude,lon:h.longitude,brightness:h.brightness,confidence:res.confidence,persistence:p.score??e.persistence,distance:facility?.distanceKm??e.distance,cls:res.classification,risk:res.risk,explanations:res.explanations,source:d.event.source,facility:facility?.name,facilityType:facility?.type,satellite:h.satellite,frp:h.frp,firmsConfidence:h.confidence,persistenceObservations:p.observations??p.hotspotCount,persistenceWindow:p.windowDays??timeWindow};setEvents(xs=>xs.map(x=>x.id===e.id?updated:x));setSelected(updated);setToast(`${updated.id} refreshed · ${updated.cls} · ${updated.confidence}%`);}catch(err){setToast(err instanceof Error?err.message:'Analysis failed')}finally{setAnalyzing(false)}};
 const simulate=async()=>{setAnalyzing(true);try{const coords=simLocation.toLowerCase().includes('mumbai')?[19.076,72.878]:simLocation.toLowerCase().includes('delhi')?[28.614,77.209]:simLocation.toLowerCase().includes('rajasthan')?[27.17,73.21]:[23.0225,72.5714];const r=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({latitude:coords[0],longitude:coords[1],brightnessKelvin:brightness,persistenceScore:persistence,industrialDistance:0.7,landCover:'industrial',location:`Simulated industrial event · ${simLocation}`})});const d=await r.json();if(!d.ok)throw new Error(d.error);const n=toEvent(d.event);setEvents(xs=>[n,...xs]);setSelected(n);setSource('SIMULATION');setToast(`Live simulation added ${n.id} · ${n.cls} · ${n.confidence}%`);setSim(false);setTimeout(()=>analyze(n),150);}catch(err){setToast(err instanceof Error?err.message:'Simulation failed')}finally{setAnalyzing(false)}};
 const generateAlert=()=>{if(alerts.includes(selected.id)){setToast(`${selected.id} is already in the alert queue`);return}setAlerts(a=>[selected.id,...a]);setToast(`Priority alert created for ${selected.id} · visible in Alerts`)};
 return <main className="app">
  <nav className="topnav"><button className="navbrand" onClick={()=>scroll('home')}><span className="brandmark"><Flame size={19}/></span><span><b>AgniDrishti</b><small>THERMAL INTELLIGENCE</small></span></button><div className="navlinks">{[['home','Overview'],['monitor','Live Monitor'],['intelligence','Intelligence'],['analytics','Analytics'],['history','History'],['alerts','Alerts']].map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>scroll(id)}>{label}{id==='alerts'&&alerts.length>0&&<em>{alerts.length}</em>}</button>)}</div><div className="navright"><span className="online"><i/> SYSTEM ONLINE</span><button className="navsimulate" onClick={()=>setSim(true)}><Zap size={15}/> Simulate</button></div></nav>
  <section id="home" className="hero section"><div className="heroCopy"><span className="eyebrow"><span className="livePulse"/> NASA FIRMS · OSM · SATELLITE · EXPLAINABLE AI</span><h1>Turn thermal anomalies into<br/><span>actionable intelligence.</span></h1><p>AgniDrishti detects hotspots, enriches them with industrial and geographic context, classifies the likely source, scores risk, and explains the evidence behind every decision.</p><div className="heroActions"><button className="primary" onClick={()=>scroll('monitor')}><Satellite size={17}/> Explore live monitor <ChevronRight size={16}/></button><button className="secondary" onClick={()=>setSim(true)}><Sparkles size={16}/> Run AI simulation</button></div><div className="heroProof"><span><ShieldCheck size={15}/> Multisource evidence</span><span><Target size={15}/> 5 source classes</span><span><Activity size={15}/> Explainable decisions</span></div></div><div className="heroVisual"><div className="orb"><div className="orbCore"><Flame size={34}/><b>{loading?'—':events.length}</b><small>ACTIVE HOTSPOTS</small></div><span className="ring r1"/><span className="ring r2"/><span className="ring r3"/><i className="scanline"/></div><div className="heroCard"><span className="label">CURRENT SIGNAL</span><b>{selected.cls}</b><span>{selected.lat.toFixed(2)}° N · {selected.lon.toFixed(2)}° E</span><strong>{selected.confidence}% <small>AI confidence</small></strong></div></div></section>
  <section className="metrics section"><Stat icon={<Flame/>} label="Active thermal events" value={loading?'…':events.length} sub={source==='POSTGRES'?'LIVE DATABASE':'DEMO / FALLBACK'}/><Stat icon={<Activity/>} label="Persistent sources" value={loading?'…':persistent} sub="70%+ historical recurrence"/><Stat icon={<AlertTriangle/>} label="High + critical" value={loading?'…':critical} sub="Risk-prioritized" hot/><Stat icon={<ShieldCheck/>} label="Average confidence" value={loading?'…':`${avg.toFixed(1)}%`} sub="Current event set"/></section>
  <section id="monitor" className="section sectionBlock">
   <SectionHeading kicker="01 · LIVE MONITOR" title="See the heat. Follow the signal." text="Move from national thermal activity to one explainable, actionable event." action={<button className="ghost" onClick={load} disabled={loading}><RefreshCw size={14}/> {loading?'Syncing':'Refresh data'}</button>}/>
   <div className="monitorGrid">
    <div className="mapShell">
     <div className="mapHeader">
      <div><span className="label">INDIA · THERMAL ACTIVITY</span><b><span className="greenDot"/> {mapMode==='density'?`NASA FIRMS ARCHIVE · ${visibleSignals.length.toLocaleString('en-IN')} DETECTIONS`:`${source==='POSTGRES'?'LIVE DATABASE':'CLASSIFIED DEMO EVENTS'} · ${visible.length} VISIBLE`}</b></div>
      <div className="mapControls">
       <div className="modeSwitch" aria-label="Map view"><button className={mapMode==='hotspots'?'active':''} onClick={()=>setMapMode('hotspots')}>Hotspots</button><button className={mapMode==='density'?'active':''} onClick={()=>setMapMode('density')}>Thermal density</button></div>
       <div className="mapTools"><button className={layersOpen?'active':''} onClick={()=>setLayersOpen(v=>!v)}><Layers3 size={14}/> Layers</button><button onClick={()=>setFilter(filter==='ALL'?'CRITICAL':'ALL')}><Target size={14}/> {filter==='ALL'?'Focus risk':'Show all'}</button></div>
      </div>
     </div>
     <div className={`timeRail ${mapMode==='density'?'enabled':'muted'}`}><span>FIRMS TIME WINDOW</span>{[1,7,30].map(n=><button key={n} className={timeWindow===n?'active':''} onClick={()=>{setTimeWindow(n);setMapMode('density')}}>{n===1?'LAST 24H':`LAST ${n} DAYS`}</button>)}<em>{mapMode==='density'?`Showing ${visibleSignals.length.toLocaleString('en-IN')} real satellite detections`:'Choose a window to open density view'}</em></div>
     <div className="mapStage">
      <LiveMap events={visible.map(e=>({id:e.id,latitude:e.lat,longitude:e.lon,risk:e.risk,confidence:e.confidence,classification:e.cls,brightness:e.brightness,persistence:e.persistence}))} densityEvents={visibleSignals} selectedId={selected.id} onSelect={id=>{const e=events.find(x=>x.id===id);if(e)selectEvent(e)}} mode={mapMode} layers={mapLayers}/>
      {mapMode==='hotspots'?<div className="classLegend"><span><i className="industrial"/>Industrial fire</span><span><i className="flare"/>Gas flare</span><span><i className="crop"/>Crop burning</span><span><i className="wildfire"/>Wildfire</span><span><i className="mining"/>Mining</span></div>:<div className="heatLegend"><span>THERMAL-RISK DENSITY</span><i/><div><small>LOW</small><small>SEVERE</small></div></div>}
      {layersOpen&&<div className="layerBox"><b>MAP LAYERS</b><label className={mapMode==='hotspots'?'disabledLayer':''}><input type="checkbox" checked={mapLayers.thermal} disabled={mapMode==='hotspots'} onChange={e=>setMapLayers(v=>({...v,thermal:e.target.checked}))}/> FIRMS density surface</label><label><input type="checkbox" checked={mapLayers.markers} onChange={e=>setMapLayers(v=>({...v,markers:e.target.checked}))}/> Classified event markers</label><label className={mapMode==='density'?'disabledLayer':''}><input type="checkbox" checked={mapLayers.halos} disabled={mapMode==='density'} onChange={e=>setMapLayers(v=>({...v,halos:e.target.checked}))}/> Operational risk rings</label><label><input type="checkbox" checked={mapLayers.labels} onChange={e=>setMapLayers(v=>({...v,labels:e.target.checked}))}/> Geographic context</label><small>Switch layers off and the corresponding map evidence disappears immediately.</small></div>}
     </div>
    </div>
    <aside className="selectedPanel">
     <div className="selectedTop"><div><span className="label">SELECTED DETECTION</span><h3>{selected.id}</h3></div><div className="statusStack"><span className={`pill ${riskClass(selected.risk)}`}>{selected.risk}</span><small>NEEDS VERIFICATION</small></div></div>
     <div className="selectedPlace"><MapPin size={15}/><span>{selected.name}<small>{selected.lat.toFixed(4)}° N · {selected.lon.toFixed(4)}° E</small></span></div>
     <div className="classification"><div><span>LIKELY SOURCE</span><b>{selected.cls}</b><small>Evidence-based classification</small></div><strong>{selected.confidence}%<small>confidence</small></strong></div>
     <div className="contextCard"><Building2 size={16}/><div><span>NEAREST MAPPED FACILITY</span><b>{selected.facility||'No named facility available'}</b><small>{selected.facilityType?`${selected.facilityType} · `:''}{selected.distance<99?`${selected.distance.toFixed(1)} km from detection`:'Proximity unavailable'}</small></div></div>
     <div className="signalGrid">
      <Signal icon={<Flame/>} label="Thermal intensity" value={`${selected.brightness} K`} note={selected.brightness>=335?'Very high':'Elevated'}/>
      <Signal icon={<Activity/>} label="Persistence" value={selected.persistenceObservations?`${selected.persistenceObservations} observations`:`${selected.persistence}% score`} note={`Across ${selected.persistenceWindow||30} days`}/>
      <Signal icon={<ShieldCheck/>} label="FIRMS confidence" value={`${selected.firmsConfidence||selected.confidence}%`} note="Detection quality"/>
      <Signal icon={<Gauge/>} label="Radiative power" value={selected.frp?`${selected.frp.toFixed(1)} MW`:'Unavailable'} note="NASA FIRMS FRP"/>
     </div>
     <div className="evidenceSummary"><div className="xaiHead"><span><Sparkles size={14}/> WHY THIS CLASSIFICATION?</span><b>{analyzing?'ANALYZING':'EVIDENCE'}</b></div>{(selected.explanations||fallbackXai).filter(x=>x.contribution>0).slice(0,3).map((x,i)=><div className="reasonRow" key={`${x.feature}-${i}`}><i>{i+1}</i><span>{x.feature}</span><strong>{Math.round(x.contribution*100)}% influence</strong></div>)}<button className="technicalToggle" onClick={()=>setTechnical(v=>!v)}>View technical evidence <ChevronDown size={13} className={technical?'open':''}/></button>{technical&&<div className="technicalEvidence">{(selected.explanations||fallbackXai).map((x,i)=><div className="xaiRow" key={`${x.feature}-${i}`}><span>{x.feature}</span><i><b style={{width:`${Math.min(100,Math.max(6,Math.abs(x.contribution)*100/0.45))}%`}}/></i><strong className={x.contribution<0?'negative':''}>{x.contribution>0?'+':''}{x.contribution.toFixed(2)}</strong></div>)}</div>}</div>
     <div className="provenance"><Clock3 size={14}/><div><b>{selected.time} · {selected.satellite||selected.source||'DEMO'}</b><span>Thermal: NASA FIRMS · Context: OSM / land cover · Decision: AgniDrishti</span></div></div>
     <div className="recommendation"><span>RECOMMENDED NEXT STEP</span><p>Compare recent imagery and the facility’s historical baseline before escalation.</p></div>
     <div className="panelActions"><button className="ghost" onClick={()=>analyze(selected)} disabled={analyzing}><RefreshCw size={14}/>{analyzing?'Running context…':'Run context analysis'}</button><button className={alerts.includes(selected.id)?'alertCreated primary':'primary'} onClick={generateAlert} disabled={alerts.includes(selected.id)}><Bell size={15}/> {alerts.includes(selected.id)?'Alert queued':'Create alert'}</button></div>
    </aside>
   </div>
  </section>
  <section id="intelligence" className="section sectionBlock"><SectionHeading kicker="02 · INTELLIGENCE" title="From hotspot to explanation." text="Every event is more than a dot on a map: it carries evidence, classification, confidence, risk and a traceable explanation."/><div className="intelGrid"><div className="evidenceCard"><div className="cardTitle"><div><span className="label">EVIDENCE STACK</span><h2>What the engine sees</h2></div><Wifi size={17}/></div>{[['01','Thermal signal','Brightness, confidence and fire radiative context'],['02','Spatial context','Distance to industrial facilities and land-cover context'],['03','Temporal history','Persistence and recurrence across the analysis window'],['04','AI decision','Class + confidence + risk generated from combined evidence']].map(([n,t,d])=><div className="evidenceRow" key={n}><b>{n}</b><div><strong>{t}</strong><span>{d}</span></div><ChevronRight size={15}/></div>)}</div><div className="decisionCard"><span className="label">CURRENT AI DECISION</span><div className="decisionClass"><Flame size={22}/><div><small>LIKELY SOURCE</small><b>{selected.cls}</b></div><strong>{selected.confidence}%</strong></div><div className="riskMeter"><span>RISK SCORE</span><i><b style={{width:`${Math.min(100,selected.risk==='CRITICAL'?94:selected.risk==='HIGH'?76:selected.risk==='MODERATE'?52:28)}%`}}/></i><em>{selected.risk}</em></div><p>The classifier combines thermal intensity, FIRMS confidence, persistence, industrial proximity and land context. The explanation above shows the contribution of each feature.</p><button className="ghost" onClick={()=>analyze(selected)} disabled={analyzing}>{analyzing?'Recomputing…':'Re-run analysis'} <ChevronRight size={14}/></button></div></div></section>
  <section id="analytics" className="section sectionBlock"><SectionHeading kicker="03 · ANALYTICS" title="Understand patterns, not isolated pixels." text="Use the event stream to identify persistence, risk concentration and source mix."/><div className="analyticsGrid"><div className="chartCard"><div className="cardTitle"><div><span className="label">30-DAY SIGNAL HISTORY</span><h2>Thermal activity trend</h2></div><span className="trend"><Activity size={14}/> Live model view</span></div><div className="bigBars">{[32,44,38,58,46,67,53,76,62,83,71,91,68,78,88,74,95,81].map((v,i)=><i key={i} style={{height:`${v}%`}}><b/></i>)}</div><div className="axis"><span>−30d</span><span>−20d</span><span>−10d</span><span>Now</span></div></div><div className="mixCard"><span className="label">CLASSIFICATION MIX</span><h2>What are we seeing?</h2><div className="mixRows">{['Industrial Fire','Gas Flare','Crop Burning','Wildfire','Mining'].map(name=>{const count=events.filter(e=>e.cls===name).length;return <div key={name}><span>{name}</span><i><b style={{width:`${Math.max(8,count/events.length*100)}%`}}/></i><strong>{count}</strong></div>})}</div></div></div></section>
  <section id="history" className="section sectionBlock"><SectionHeading kicker="04 · HISTORICAL INTELLIGENCE" title="Persistence turns heat into context." text="Repeated detections can distinguish persistent industrial sources from transient events."/><div className="historyGrid"><div className="historyLead"><div className="historyNumber">{selected.persistence}<span>%</span></div><div><span className="label">SELECTED EVENT PERSISTENCE</span><h2>{selected.persistence>=70?'Persistent thermal source':'Transient thermal event'}</h2><p>Persistence is contextual evidence, not proof of cause. Analysts can combine it with location, land cover and imagery before taking action.</p></div></div><div className="historyTimeline">{Array.from({length:10},(_,i)=>{const v=Math.max(10,Math.round((selected.persistence/100)*(55+(i%4)*11)));return <div key={i}><span>Day {i+1}</span><i style={{height:`${v}%`}}/></div>})}</div></div></section>
  <section id="alerts" className="section sectionBlock"><SectionHeading kicker="05 · RISK & RESPONSE" title="Move from detection to action." text="Priority alerts are created from selected intelligence and remain visible as an analyst queue."/><div className="alertsGrid"><div className="alertQueue"><div className="cardTitle"><div><span className="label">PRIORITY QUEUE</span><h2>{alerts.length?`${alerts.length} active alert${alerts.length>1?'s':''}`:'No alerts yet'}</h2></div><Bell size={17}/></div>{alerts.length?alerts.map(id=>{const e=events.find(x=>x.id===id)||selected;return <button className="alertRow" key={id} onClick={()=>analyze(e)}><span className={`dot ${riskClass(e.risk)}`}/><div><b>{id}</b><small>{e.cls} · {e.name}</small></div><span className={`pill ${riskClass(e.risk)}`}>{e.risk}</span><ChevronRight size={15}/></button>}):<div className="emptyAlert"><Bell size={20}/><b>Alert queue is clear</b><span>Select an event and generate a priority alert.</span></div>}</div><div className="responseCard"><span className="label">RECOMMENDED WORKFLOW</span><h2>Detect → verify → respond</h2><div><b>01</b><span>Review thermal evidence and confidence.</span></div><div><b>02</b><span>Inspect industrial proximity and historical pattern.</span></div><div><b>03</b><span>Open satellite/context evidence for verification.</span></div><div><b>04</b><span>Escalate only after analyst or ground verification.</span></div></div></div></section>
  <section className="section cta"><div><span className="eyebrow">SIMULATION LAB · SAFE DEMO MODE</span><h2>Want to see the intelligence pipeline move?</h2><p>Generate a new hotspot, run the classifier, update the map and push the result into the intelligence feed.</p></div><button className="primary" onClick={()=>setSim(true)}><Zap size={17}/> Launch simulation</button></section>
  <footer><div><span className="brandmark small"><Flame size={15}/></span><b>AgniDrishti</b> · Team WINFINITY</div><span><i/> Pipeline operational · {source==='POSTGRES'?'LIVE DATABASE':'DEMO / SIMULATION'}</span><span>© 2026</span></footer>
  {toast&&<div className="toast"><Sparkles size={15}/><span>{toast}</span><button onClick={()=>setToast('')}>×</button></div>}
  {sim&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSim(false)}}><div className="modal"><button className="modalClose" onClick={()=>setSim(false)}>×</button><div className="modalIcon"><Zap size={18}/></div><span className="label">SIMULATION LAB</span><h2>Create a new thermal event</h2><p>This is a real application flow: the event is classified by the same classifier, receives feature contributions, appears on the map and is added to Recent Intelligence.</p><label>Scenario location<input value={simLocation} onChange={e=>setSimLocation(e.target.value)}/></label><label>Thermal intensity <b>{brightness} K</b><input type="range" min="280" max="380" value={brightness} onChange={e=>setBrightness(Number(e.target.value))}/></label><label>Historical persistence <b>{persistence}%</b><input type="range" min="0" max="100" value={persistence} onChange={e=>setPersistence(Number(e.target.value))}/></label><div className="flow"><span>HOTSPOT</span><ChevronRight/><span>CONTEXT</span><ChevronRight/><span>CLASSIFY</span><ChevronRight/><span>XAI</span></div><button className="primary full" onClick={simulate} disabled={analyzing}><Sparkles size={16}/> {analyzing?'Running pipeline…':'Run AI simulation'}</button></div></div>}
 </main>;
}
function SectionHeading({kicker,title,text,action}:{kicker:string;title:string;text:string;action?:ReactNode}){return <div className="sectionHeading"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Stat({icon,label,value,sub,hot}:{icon:ReactNode;label:string;value:string|number;sub:string;hot?:boolean}){return <div className="statCard"><div className={`statIcon ${hot?'hot':''}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div><div className="spark">{[1,2,3,4,5,6,7].map(i=><i key={i}/>)}</div></div>}
function Signal({icon,label,value,note}:{icon:ReactNode;label:string;value:string;note:string}){return <div className="signal"><span className="signalIcon">{icon}</span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></div>}
