'use client';

import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, Clock3, MapPin, Network, RefreshCw, ShieldCheck, TrendingUp } from 'lucide-react';

type EventLike = { id:string; name:string; lat:number; lon:number; cls:string; confidence:number; risk:string; brightness:number; persistence:number; detectedAt?:string; time?:string };
type Props = { events:EventLike[]; selected:EventLike; onSelect?:(event:EventLike)=>void };
const radiusKm=25;
function distanceKm(a:EventLike,b:EventLike){const r=6371,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lon-a.lon)*p,x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(x));}
function timeMs(e:EventLike){return e.detectedAt?Date.parse(e.detectedAt):Number.NaN;}
export default function CrossEventIntelligence({events,selected,onSelect}:Props){
 const [windowMode,setWindowMode]=useState<'24h'|'7d'>('24h');
 const hours=windowMode==='24h'?24:168;
 const related=useMemo(()=>events.filter(e=>e.id!==selected.id).map(event=>({event,distance:distanceKm(selected,event)})).filter(({event,distance})=>{const a=timeMs(selected),b=timeMs(event);return distance<=radiusKm&&(Number.isNaN(a)||Number.isNaN(b)||Math.abs(a-b)<=hours*3600000)}).sort((a,b)=>a.distance-b.distance),[events,selected,hours]);
 const cluster=[selected,...related.map(x=>x.event)];
 const avgConfidence=Math.round(cluster.reduce((s,e)=>s+e.confidence,0)/Math.max(1,cluster.length));
 const avgBrightness=cluster.reduce((s,e)=>s+e.brightness,0)/Math.max(1,cluster.length);
 const classes=[...new Set(cluster.map(e=>e.cls))];
 const score=Math.min(99,Math.round(45+Math.min(30,related.length*8)+(classes.length===1?12:4)+(avgConfidence>=85?10:0)));
 const pattern=related.length>=4?'UNUSUAL CLUSTERING':related.length>=2?'CORRELATED ACTIVITY':'ISOLATED SIGNAL';
 return <section className="crossEventWorkspace">
  <div className="crossEventToolbar"><div><span className="label">CROSS-EVENT INTELLIGENCE</span><h2>Connect the signals.</h2><p>Find nearby thermal events that may belong to the same emerging activity pattern.</p></div><div className="crossEventControls"><button className={windowMode==='24h'?'active':''} onClick={()=>setWindowMode('24h')}>24 hours</button><button className={windowMode==='7d'?'active':''} onClick={()=>setWindowMode('7d')}>7 days</button><button className="ghost" onClick={()=>setWindowMode(windowMode)}><RefreshCw size={14}/> Refresh cluster</button></div></div>
  <div className="crossEventGrid"><div className="crossEventMap cardSurface"><div className="cardTitle"><div><span className="label">REGIONAL EVENT MAP</span><h3>{cluster.length} events in the investigation window</h3></div><Network size={18}/></div><div className="clusterCanvas"><div className="clusterHalo"/><div className="clusterCentre"><Activity size={18}/><b>{selected.id}</b><small>SELECTED EVENT</small></div>{related.map(({event,distance},i)=>{const angle=i/Math.max(1,related.length)*Math.PI*2-Math.PI/2,spread=Math.min(42,18+distance*1.2);return <button key={event.id} className="clusterNode" style={{left:`${50+Math.cos(angle)*spread}%`,top:`${50+Math.sin(angle)*spread}%`}} onClick={()=>onSelect?.(event)}><span className={`dot ${event.risk.toLowerCase()}`}/><b>{event.id}</b></button>})}{related.map(({event,distance},i)=><span key={`line-${event.id}`} className="clusterLine" style={{transform:`rotate(${i/Math.max(1,related.length)*360-90}deg)`,height:`${Math.min(42,18+distance*1.2)}%`}}/>)}<span className="clusterLegend"><MapPin size={12}/> Radius {radiusKm} km · {windowMode==='24h'?'24 hours':'7 days'}</span></div></div>
   <div className="clusterInsights cardSurface"><div className="cardTitle"><div><span className="label">CLUSTER INTELLIGENCE</span><h3>Possible related activity</h3></div><span className={`pill ${related.length>=2?'high':'moderate'}`}>{pattern}</span></div><div className="clusterScore"><strong>{score}%</strong><span>correlation score</span><i><b style={{width:`${score}%`}}/></i></div><div className="clusterStats"><div><small>RELATED EVENTS</small><b>{related.length}</b></div><div><small>AVERAGE CONFIDENCE</small><b>{avgConfidence}%</b></div><div><small>AVG BRIGHTNESS</small><b>{avgBrightness.toFixed(1)} K</b></div><div><small>CLASS MIX</small><b>{classes.length} types</b></div></div><div className="clusterReason"><ShieldCheck size={15}/><div><b>Why these events are connected</b><span>Spatial proximity, matching observation windows, and comparable thermal intensity.</span></div></div><p className="decisionNote">Correlation is an investigative signal, not proof that the events share one cause.</p></div></div>
  <div className="crossEventBottom"><div className="eventList cardSurface"><div className="cardTitle"><div><span className="label">RELATED EVENTS</span><h3>Investigation candidates</h3></div><TrendingUp size={17}/></div>{related.length?related.map(({event,distance})=><button className="relatedEvent" key={event.id} onClick={()=>onSelect?.(event)}><span className={`dot ${event.risk.toLowerCase()}`}/><span><b>{event.id}</b><small>{event.cls} · {event.time||'time unavailable'}</small></span><strong>{distance.toFixed(1)} km</strong></button>):<div className="emptyCluster"><AlertTriangle size={18}/><b>No correlated events found</b><span>Try the 7-day window or select another hotspot.</span></div>}</div><div className="patternCard cardSurface"><div className="cardTitle"><div><span className="label">EMERGING PATTERN</span><h3>Regional change signal</h3></div><Clock3 size={17}/></div><div className="patternRow"><span className="patternIcon"><Activity size={16}/></span><div><b>{pattern}</b><span>{related.length?`${related.length} nearby events could warrant joint review.`:'No nearby events currently meet the correlation rule.'}</span></div></div><div className="patternAction"><button className="ghost" onClick={()=>onSelect?.(selected)}><RefreshCw size={14}/> Recenter on selected event</button></div></div></div>
 </section>;
}
