'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Leaflet from 'leaflet';
import {terrainTiles,terrainOptions,loadIndiaBoundaries,addIndiaBoundaries} from '@/lib/india-map';

export type MapMode='detections'|'density';
export type MapLayers={facilities:boolean;halos:boolean;labels:boolean;imagery:boolean};
export type ThermalSignal={modelPrediction?:any;datasetLabel?:any;id:string;latitude:number;longitude:number;brightness:number;frp:number;date:string;time:string;confidence:number;satellite:string;persistenceDays:number;persistenceObservations:number;persistenceScore:number};
export type FacilityPoint={name:string;type:string;latitude:number;longitude:number;distanceKm:number};
type MapEvent={id:string;latitude:number;longitude:number;risk:string;confidence:number;classification:string;brightness:number;persistence:number;detectedAt?:string;time?:string};
const colours:Record<string,string>={'Industrial Fire':'#f2543f','Gas Flare':'#9258d8','Crop Burning':'#e9a432','Wildfire':'#39ad69','Mining thermal source':'#318fca','Mining':'#318fca','Unclassified thermal anomaly':'#9bb4c6'};
const RADIUS_KM=25; const WINDOW_HOURS=24;
function distanceKm(a:MapEvent,b:MapEvent){const p=Math.PI/180,lat1=a.latitude*p,lat2=b.latitude*p,dLat=(b.latitude-a.latitude)*p,dLon=(b.longitude-a.longitude)*p,h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 6371*2*Math.asin(Math.min(1,Math.sqrt(h)));}
function eventTime(e:MapEvent){const raw=e.detectedAt||e.time; if(!raw)return null;const value=Date.parse(raw);return Number.isFinite(value)?value:null;}
function buildClusters(events:MapEvent[]){const usable=events.filter(e=>Number.isFinite(e.latitude)&&Number.isFinite(e.longitude)&&Math.abs(e.latitude)<=90&&Math.abs(e.longitude)<=180);const seen=new Set<string>();const result:{id:string;events:MapEvent[];lat:number;lon:number;radius:number}[]=[];for(const seed of usable){if(seen.has(seed.id))continue;const queue=[seed];const members:MapEvent[]=[];seen.add(seed.id);while(queue.length){const current=queue.shift()!;members.push(current);for(const candidate of usable){if(seen.has(candidate.id))continue;const a=eventTime(current),b=eventTime(candidate);const temporal=a===null||b===null||Math.abs(a-b)<=WINDOW_HOURS*3600000;if(temporal&&distanceKm(current,candidate)<=RADIUS_KM){seen.add(candidate.id);queue.push(candidate);}}}if(members.length<2)continue;const lat=members.reduce((s,e)=>s+e.latitude,0)/members.length;const lon=members.reduce((s,e)=>s+e.longitude,0)/members.length;const center={...members[0],latitude:lat,longitude:lon};result.push({id:`cluster-${result.length+1}`,events:members,lat,lon,radius:Math.max(5,...members.map(e=>distanceKm(center,e)))});}return result;}

export default function LiveMap({events,densityEvents,facilities,selectedId,onSelect,mode,layers}:{events:MapEvent[];densityEvents:ThermalSignal[];facilities:FacilityPoint[];selectedId:string;onSelect:(id:string)=>void;mode:MapMode;layers:MapLayers}){
 const [mapError,setMapError]=useState(''); const officialLabels=useRef<Leaflet.LayerGroup|null>(null); const host=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),leaflet=useRef<typeof Leaflet|null>(null),drawn=useRef<any[]>([]),tiles=useRef<{street:any;satellite:any}|null>(null),[mapReady,setMapReady]=useState(false);
 useEffect(()=>{let cancelled=false,observer:ResizeObserver|undefined;(async()=>{const L=(await import('leaflet')).default;await import('leaflet.heat');const boundaries=await loadIndiaBoundaries();if(cancelled||!host.current||mapRef.current)return;const map=L.map(host.current,{zoomControl:true,attributionControl:true}).setView([22.7,79.2],5);const street=L.tileLayer(terrainTiles,terrainOptions);const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri',maxZoom:19});street.addTo(map);officialLabels.current=addIndiaBoundaries(L,map,boundaries);leaflet.current=L;tiles.current={street,satellite};mapRef.current=map;observer=new ResizeObserver(()=>map.invalidateSize({pan:false}));observer.observe(host.current);setMapReady(true)})().catch(e=>{if(!cancelled)setMapError(e instanceof Error?e.message:'Map unavailable')});return()=>{cancelled=true;observer?.disconnect();mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current,L=leaflet.current;if(!map||!tiles.current||!L)return;let cancelled=false,timer:ReturnType<typeof setTimeout>|undefined;const draw=()=>{if(cancelled||!host.current)return;map.invalidateSize({pan:false});drawn.current.forEach(x=>map.removeLayer(x));drawn.current=[];const {street,satellite}=tiles.current!;if(layers.imagery){if(map.hasLayer(street))map.removeLayer(street);if(!map.hasLayer(satellite))satellite.addTo(map)}else{if(map.hasLayer(satellite))map.removeLayer(satellite);if(!map.hasLayer(street))street.addTo(map)}
 if(mode==='density'&&densityEvents.length&&(L as any).heatLayer){const heat=(L as any).heatLayer(densityEvents.map(x=>[x.latitude,x.longitude,Math.min(1,.18+(x.brightness-280)/100+x.frp/500)]),{radius:18,blur:23,maxZoom:8}).addTo(map);drawn.current.push(heat)}
 if(mode==='detections'){const clusters=buildClusters(events);clusters.forEach(cluster=>{const colour=cluster.events.some(e=>e.risk==='CRITICAL')?'#f2543f':'#38bdf8';const boundary=L.circle([cluster.lat,cluster.lon],{radius:cluster.radius*1000,color:colour,weight:2,fillColor:colour,fillOpacity:.08,dashArray:'7 6'}).addTo(map);boundary.bindTooltip(`<b>${cluster.id}</b><br>${cluster.events.length} connected events<br>${cluster.radius.toFixed(1)} km radius · ${WINDOW_HOURS}h window`);boundary.on('click',()=>onSelect(cluster.events[0].id));drawn.current.push(boundary);for(const event of cluster.events){const line=L.polyline([[cluster.lat,cluster.lon],[event.latitude,event.longitude]],{color:colour,weight:1,opacity:.55,dashArray:'4 5'}).addTo(map);drawn.current.push(line);}});events.forEach(e=>{const selected=e.id===selectedId,c=colours[e.classification]||'#9bb4c6';if(layers.halos&&e.risk!=='MODERATE'){const halo=L.circle([e.latitude,e.longitude],{radius:e.risk==='CRITICAL'?26000:16000,color:c,weight:1,fillColor:c,fillOpacity:.06,opacity:.32}).addTo(map);drawn.current.push(halo)}const marker=L.circleMarker([e.latitude,e.longitude],{radius:selected?8:4,color:selected?'#fff':c,weight:selected?2:1,fillColor:c,fillOpacity:.9}).addTo(map);marker.bindTooltip(`<b>${e.classification}</b><br>${e.brightness.toFixed(1)} K`);marker.on('click',()=>onSelect(e.id));drawn.current.push(marker)});}
 if(layers.facilities)facilities.forEach(f=>{const m=L.circleMarker([f.latitude,f.longitude],{radius:5,color:'#65d5ff',weight:2,fillColor:'#071522',fillOpacity:1}).addTo(map);m.bindTooltip(`<b>${f.name}</b><br>${f.type} · ${f.distanceKm.toFixed(1)} km`);drawn.current.push(m)});if(officialLabels.current){if(layers.labels&&!map.hasLayer(officialLabels.current))officialLabels.current.addTo(map);else if(!layers.labels&&map.hasLayer(officialLabels.current))map.removeLayer(officialLabels.current)}};timer=setTimeout(draw,0);return()=>{cancelled=true;if(timer)clearTimeout(timer)}},[events,densityEvents,facilities,selectedId,onSelect,mode,layers,mapReady]);
 return <div ref={host} className="liveMap" aria-label="Interactive thermal activity map">{mapError&&<p role="alert">{mapError}</p>}</div>;
}
