'use client';

import { useEffect, useState } from 'react';
import CrossEventIntelligence from '@/components/CrossEventIntelligence';
import styles from '@/components/CrossEventIntelligence.module.css';

type EventLike={id:string;name:string;lat:number;lon:number;cls:string;confidence:number;risk:string;brightness:number;persistence:number;detectedAt?:string;time?:string;frp?:number;nearbyFacilities?:number};
function mapEvent(e:any):EventLike{return{id:String(e.id),name:e.location||e.name||`${e.classification||'Thermal event'} · ${Number(e.latitude).toFixed(2)}, ${Number(e.longitude).toFixed(2)}`,lat:Number(e.latitude),lon:Number(e.longitude),cls:e.classification||e.cls||'Unknown',confidence:Number(e.confidence)||0,risk:e.risk||'MODERATE',brightness:Number(e.brightnessKelvin)||0,persistence:Number(e.persistenceScore)||0,frp:Number(e.frp)||Number(e.frpMw)||0,nearbyFacilities:Number(e.nearbyFacilities)||0,detectedAt:e.detectedAt,time:e.detectedAt?new Date(e.detectedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})+' IST':e.time};}
export default function IntelligencePage(){const[events,setEvents]=useState<EventLike[]>([]);const[selected,setSelected]=useState<EventLike|null>(null);const[error,setError]=useState('');useEffect(()=>{fetch('/api/events',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load live events');return d;}).then(d=>{const mapped=(d.events||[]).map(mapEvent).filter((e:EventLike)=>Number.isFinite(e.lat)&&Number.isFinite(e.lon));setEvents(mapped);const requested=new URLSearchParams(window.location.search).get('event');setSelected(mapped.find((e:EventLike)=>e.id===requested)||mapped[0]||null);}).catch(e=>setError(e.message||'Unable to load live events'));},[]);return <main className="app"><section className="section sectionBlock"><div className={styles.workspace}>{error?<div className="emptyCluster">{error}</div>:!events.length?<div className="emptyCluster">No live thermal events available.</div>:<CrossEventIntelligence events={events} selected={selected||events[0]} onSelect={setSelected}/>}</div></section></main>;}
